#!/usr/bin/env python3
"""
Merge all per-domain collection files into one master collection.

Usage:
    python3 api-collections/merge.py

Run this every time a domain collection file is updated, then commit
both the domain file AND the generated marketplace_api.collection.json.
"""

import json
import os
import sys

COLLECTIONS_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(COLLECTIONS_DIR, "marketplace_api.collection.json")

MASTER_INFO = {
    "name": "Marketplace API",
    "_postman_id": "marketplace-api-master",
    "description": "Full Marketplace API — all modules. Auto-generated by api-collections/merge.py. Do not edit manually.",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
}

MASTER_AUTH = {
    "type": "bearer",
    "bearer": [{"key": "token", "value": "{{access_token}}", "type": "string"}],
}


def load_domain_files():
    files = sorted(
        f for f in os.listdir(COLLECTIONS_DIR)
        if f.endswith(".collection.json") and f != "marketplace_api.collection.json"
    )
    if not files:
        print("ERROR: No domain collection files found in api-collections/", file=sys.stderr)
        sys.exit(1)
    return files


def merge_variables(domain_files):
    seen = set()
    merged = []
    for fname in domain_files:
        path = os.path.join(COLLECTIONS_DIR, fname)
        with open(path) as f:
            col = json.load(f)
        for var in col.get("variable", []):
            if var["key"] not in seen:
                seen.add(var["key"])
                merged.append(var)
    return merged


def merge_items(domain_files):
    items = []
    for fname in domain_files:
        path = os.path.join(COLLECTIONS_DIR, fname)
        with open(path) as f:
            col = json.load(f)
        folder_items = col.get("item", [])
        if not folder_items:
            continue
        if len(folder_items) == 1:
            items.append(folder_items[0])
        else:
            display_name = col["info"]["name"].replace("Marketplace API — ", "")
            items.append({"name": display_name, "item": folder_items})
    return items


def main():
    domain_files = load_domain_files()
    print(f"Found {len(domain_files)} domain collection files:")
    for f in domain_files:
        print(f"  {f}")

    master = {
        "info": MASTER_INFO,
        "auth": MASTER_AUTH,
        "variable": merge_variables(domain_files),
        "item": merge_items(domain_files),
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(master, f, indent=2, ensure_ascii=False)

    size_kb = os.path.getsize(OUTPUT_FILE) / 1024
    print(f"\nGenerated: {OUTPUT_FILE} ({size_kb:.1f} KB)")
    print("Next steps:")
    print("  git add api-collections/<domain>.collection.json api-collections/marketplace_api.collection.json")
    print("  git commit -m 'docs(api-collections): update <domain> collection'")


if __name__ == "__main__":
    main()
